### ISSUE TITLE
Warnings in 2021.12 beta

### ISSUE THREAD

**Issue by VDRainer** [bushvin/hass-integrations#13]
HA Startup log:
```
2021-12-08 08:46:42 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that accessed discovery_info['hostname'] instead of discovery_info.hostname; this will fail in version 2022.6. Please report issue to the custom component author for mopidy using this method at custom_components/mopidy/config_flow.py, line 110: mdns_address = discovery_info["hostname"][:-1]
```
There is no rush, time until June 2022. :smile:

**Comment by bushvin** [comment]
Thank you for reading the debug logs ;)

Will fix soon.

**Comment by AdmiralStipe** [comment]
Any progress on this? I know that HA version 2022.6 is not coming anytime soon yet, but it bothers my OCD ( :smile ) to have this warning recorded in my log all the time. 
And btw it's not only hostname, most likely the same issue will appear with "host" and "port" and probably something else also...

**Comment by bushvin** [comment]
I'm really, really, really sorry about keeping your OCD anxious... We really don't want that ;)

I believe I have fixed the code, feel free to test and provide feedback!

**Comment by chatziko** [comment]
Thanks for the fix.

Minor issue: the fix doesn't seem to be included in the 1.4.2 release (commit 1ad58ac, before the fix). I noticed it cause I upgraded via HACS and still getting the warning.

**Comment by bushvin** [comment]
This is weird.. I thought I added the tag after merging the PR...

**Comment by bushvin** [comment]
Bumped the version to 1.4.3 and all looks good now
thanks for raising this, @chatziko

**Comment by chatziko** [comment]
The update worked fine, thanks.
 
On the other hand, I'm getting this now in the log:
```


Logger: homeassistant
Source: custom_components/mopidy/config_flow.py:136
Integration: Mopidy (documentation)
First occurred: 11:22:47 AM (1 occurrences)
Last logged: 11:22:47 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mopidy/config_flow.py", line 136, in async_step_zeroconf
    getattr(discovery_info, CONF_NAME)[: len(getattr(discovery_info, CONF_TYPE) +1) * -1]
TypeError: can only concatenate str (not "int") to str
```

**Comment by bushvin** [comment]
Thanks for raising this.
I fixed it, but haven't updated tags or release.

**Comment by chatziko** [comment]
Thanks! I'll try it when I find some time.
